export const REGION_CATALOG = [
  {
    code: 'REGION_DE_VALLES_CENTRALES_ZONA_NORTE',
    name: 'REGIÓN DE VALLES CENTRALES ZONA NORTE',
    sortOrder: 1,
    delegations: [
      { name: 'TLACOLULA', sortOrder: 1 },
      { name: 'MITLA', sortOrder: 2 },
      { name: 'EL RETIRO', sortOrder: 3 },
      { name: 'IXTLÁN DE JUÁREZ', sortOrder: 4 },
      { name: 'ETLA', sortOrder: 5 },
    ],
  },
  {
    code: 'REGION_DE_VALLES_CENTRALES_ZONA_SUR',
    name: 'REGIÓN DE VALLES CENTRALES ZONA SUR',
    sortOrder: 2,
    delegations: [
      { name: 'MIAHUATLÁN DE P.D.', sortOrder: 1 },
      { name: 'ZAACHILA', sortOrder: 2 },
      { name: 'OCOTLÁN', sortOrder: 3 },
      { name: 'EJUTLA DE CRESPO', sortOrder: 4 },
      { name: 'ZIMATLÁN', sortOrder: 5 },
      { name: 'SOLA DE VEGA', sortOrder: 6 },
    ],
  },
  {
    code: 'REGION_COSTA_ZONA_ORIENTE',
    name: 'REGIÓN COSTA ZONA ORIENTE',
    sortOrder: 3,
    delegations: [
      { name: 'HUATULCO', sortOrder: 1 },
      { name: 'PUERTO ESCONDIDO', sortOrder: 2 },
      { name: 'POCHUTLA', sortOrder: 3 },
      { name: 'SANTOS REYES NOPALA', sortOrder: 4 },
    ],
  },
  {
    code: 'REGION_COSTA_ZONA_PONIENTE',
    name: 'REGIÓN COSTA ZONA PONIENTE',
    sortOrder: 4,
    delegations: [
      { name: 'PINOTEPA NACIONAL', sortOrder: 1 },
      { name: 'JUQUILA', sortOrder: 2 },
      { name: 'RÍO GRANDE', sortOrder: 3 },
      { name: 'JAMILTEPEC', sortOrder: 4 },
      { name: 'CACAHUATEPEC', sortOrder: 5 },
    ],
  },
  {
    code: 'REGION_DEL_ISTMO_ZONA_NORTE',
    name: 'REGIÓN DEL ISTMO ZONA NORTE',
    sortOrder: 5,
    delegations: [
      { name: 'MATIAS ROMERO', sortOrder: 1 },
      { name: 'TAPANATEPEC', sortOrder: 2 },
      { name: 'MA. LOMBARDO', sortOrder: 3 },
      { name: 'SAN JUAN GUICHICOVI', sortOrder: 4 },
    ],
  },
  {
    code: 'REGION_DEL_ISTMO_ZONA_SUR',
    name: 'REGIÓN DEL ISTMO ZONA SUR',
    sortOrder: 6,
    delegations: [
      { name: 'SALINA CRUZ', sortOrder: 1 },
      { name: 'CIUDAD IXTEPEC', sortOrder: 2 },
      { name: 'JUCHITÁN', sortOrder: 3 },
      { name: 'TEHUANTEPEC', sortOrder: 4 },
    ],
  },
  {
    code: 'REGION_DE_LA_MIXTECA',
    name: 'REGIÓN DE LA MIXTECA',
    sortOrder: 7,
    delegations: [
      { name: 'HUAJUAPAN DE LEÓN', sortOrder: 1 },
      { name: 'NOCHIXTLÁN', sortOrder: 2 },
      { name: 'TAMAZULAPAN', sortOrder: 3 },
      { name: 'TLAXIACO', sortOrder: 4 },
      { name: 'S.P. Y S.P. TEPOSCOLULA', sortOrder: 5 },
      { name: 'PUTLA DE GRO.', sortOrder: 6 },
      { name: 'JUXTLAHUACA', sortOrder: 7 },
    ],
  },
  {
    code: 'REGION_DE_LA_CUENCA',
    name: 'REGIÓN DE LA CUENCA',
    sortOrder: 8,
    delegations: [
      { name: 'TUXTEPEC', sortOrder: 1 },
      { name: 'TEMASCAL', sortOrder: 2 },
      { name: 'COSOLAPA', sortOrder: 3 },
      { name: 'VALLE NACIONAL', sortOrder: 4 },
      { name: 'ACATLÁN DE PÉREZ FIGUEROA', sortOrder: 5 },
      { name: 'LOMA BONITA', sortOrder: 6 },
      { name: 'JALAPA DE DÍAZ', sortOrder: 7 },
    ],
  },
  {
    code: 'REGION_DE_LA_CANADA',
    name: 'REGIÓN DE LA CAÑADA',
    sortOrder: 9,
    delegations: [
      { name: 'TEOTITLÁN DE FLORES MAGÓN', sortOrder: 1 },
      { name: 'CUICATLÁN', sortOrder: 2 },
      { name: 'HUAUTLA DE JIMÉNEZ', sortOrder: 3 },
    ],
  },
  {
    code: 'REGION_CENTRO',
    name: 'CENTRO',
    sortOrder: 10,
    delegations: [
      { name: 'JEFE OPERATIVO', sortOrder: 1 },
      { name: 'COORDINACION', sortOrder: 2 },
    ],
  },
] as const;
